version: "3.8"

services:
  e-commerce:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce
    working_dir: /app
    command: npm start
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - e-commerce
    networks:
      - app-network

networks:
  app-network:
    driver: bridge